from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ReceiverRegister/$', views.receiver_register, name='ReceiverRegister'),
    url(r'^ReceiverLogin/$', views.receiver_login, name='ReceiverLogin'),
    url(r'^ReceiverHome/$', views.receiver_home, name='ReceiverHome'),
    url(r'^ReceiverProfile/$', views.receiver_profile, name='ReceiverProfile'),
    url(r'^ReceiverViewFiles/$', views.receiver_view_files, name='ReceiverViewFiles'),
    url(r'^ReceiverSearchFiles/$', views.receiver_search_files, name='ReceiverSearchFiles'),
    url(r'^ReceiverSearchFileResult/(?P<filename>\S+)$', views.receiver_search_file_result, name='ReceiverSearchFileResult'),
    url(r'^ReceiverDownloadSearchFile/$', views.receiver_download_search_file, name='ReceiverDownloadSearchFile'),
    url(r'^ReceiverDownloadedFile/$', views.receiver_downloaded_file, name='ReceiverDownloadedFile'),
    url(r'^ReceiverReqPublicKey/$', views.receiver_req_publickey, name='ReceiverReqPublicKey'),
    url(r'^ReceiverReqSecretKey/$', views.receiver_req_secretkey, name='ReceiverReqSecretKey'),
    url(r'^ReceiverResPublicKey/$', views.receiver_res_publickey, name='ReceiverResPublicKey'),
    url(r'^ReceiverResSecretKey/$', views.receiver_res_secretkey, name='ReceiverResSecretKey'),
    url(r'^ReceiverDownloadFile/$', views.receiver_download_file, name='ReceiverDownloadFile'),
    url(r'^ReceiverProfileImage/$', views.receiver_profile_image, name='ReceiverProfileImage'),
    url(r'^ReceiverLogout/$', views.receiver_logout, name='ReceiverLogout'),

    url(r'^SenderRegister/$', views.sender_register, name='SenderRegister'),
    url(r'^SenderLogin/$', views.sender_login, name='SenderLogin'),
    url(r'^SenderHome/$', views.sender_home, name='SenderHome'),
    url(r'^UploadFile/$', views.upload_file, name='UploadFile'),
    url(r'^UploadFiles/$', views.upload_files, name='UploadFiles'),
    url(r'^UploadedFiles/$', views.uploaded_files, name='UploadedFiles'),
    url(r'^VerifyFiles/$', views.verify_files, name='VerifyFiles'),
    url(r'^VerifiedFiles/(?P<filename>\S+)$', views.verified_files, name='VerifiedFiles'),
    url(r'^RecoverFiles/(?P<filename>\S+)$', views.recover_files, name='RecoverFiles'),
    url(r'^ViewFiles/$', views.view_files, name='ViewFiles'),
    url(r'^ViewedFiles/(?P<filename>\S+)$', views.viewed_files, name='ViewedFiles'),
    url(r'^SenderLogout/$', views.sender_logout, name='SenderLogout'),

    url(r'^CloudLogin/$', views.cloud_login, name='CloudLogin'),
    url(r'^CloudHome/$', views.cloud_home, name='CloudHome'),
    url(r'^CloudViewSenders/$', views.cloud_view_senders, name='CloudViewSenders'),
    url(r'^CloudVerifySender/(?P<id>\w+)$', views.cloud_verify_sender, name='CloudVerifySender'),
    url(r'^CloudViewReceivers/$', views.cloud_view_receivers, name='CloudViewReceivers'),
    url(r'^CloudVerifyReceiver/(?P<id>\w+)$', views.cloud_verify_receiver, name='CloudVerifyReceiver'),
    url(r'^CloudSenderFiles/$', views.cloud_sender_files, name='CloudSenderFiles'),
    url(r'^CloudViewedFile/(?P<filename>\S+)$', views.cloud_viewed_file, name='CloudViewedFile'),
    url(r'^CloudViewAttackers/$', views.cloud_view_attackers, name='CloudViewAttackers'),
    url(r'^CloudFilesWithPublicKey/$', views.cloud_files_with_publickey, name='CloudFilesWithPublicKey'),
    url(r'^CloudPublicKeyPermission/$', views.cloud_publickey_permission, name='CloudPublicKeyPermission'),
    url(r'^CloudPublicKeyPermissionGranted/(?P<id>\w+)/(?P<filename>\S+)$', views.cloud_publicKey_permission_granted, name='CloudPublicKeyPermissionGranted'),
    url(r'^CloudShareSecretKey/$', views.cloud_share_secretkey, name='CloudShareSecretKey'),
    url(r'^CloudSharedSecretKey/(?P<id>\w+)/(?P<filename>\S+)$', views.cloud_shared_secretkey, name='CloudSharedSecretKey'),
    url(r'^CloudAttackersGraph/$', views.cloud_attackers_graph, name='CloudAttackersGraph'),
    url(r'^CloudComparisonGraph/$', views.cloud_comparison_graph, name='CloudComparisonGraph'),
    url(r'^CloudTrapdoorGraph/$', views.cloud_trapdoor_graph, name='CloudTrapdoorGraph'),
    
    url(r'^CloudLogout/$', views.cloud_logout, name='CloudLogout'),

]
